create table Instructor (
	IID INT,
	name VARCHAR(30),
	title VARCHAR(20),
	dept VARCHAR(20),
	gender VARCHAR(10)
);
insert into Instructor (IID, name, title, dept, gender) values (1, 'Erv Dublin', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (2, 'Dusty Carrodus', 'Associate Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (3, 'Baily Tift', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (4, 'Gunner Ick', 'Associate Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (5, 'Elmo Lauderdale', 'Full Professor', 'Physics', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (6, 'Monti Bims', 'Full Professor', 'Nursing', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (7, 'Cello Juares', 'Assistant Professor', 'Chemistry', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (8, 'Matteo Scutcheon', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (9, 'Kippie Matejovsky', 'Associate Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (10, 'Hewe Patek', 'Associate Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (11, 'Meggi Lesper', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (12, 'Lexine Newbold', 'Full Professor', 'Physics', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (13, 'Farly Instrell', 'Assistant Professor', 'Business', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (14, 'Irina Feldbau', 'Assistant Professor', 'Art', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (15, 'Ingunna Gascone', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (16, 'Gael Woollin', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (17, 'Weber Wolver', 'Associate Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (18, 'Nomi Cutting', 'Assistant Professor', 'Physics', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (19, 'Marley Todeo', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (20, 'Chick Badgers', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (21, 'Archer MacSharry', 'Assistant Professor', 'Nursing', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (22, 'Edythe Bradock', 'Associate Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (23, 'Teodorico Cairney', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (24, 'Michaela Sam', 'Full Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (25, 'Mead Wyleman', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (26, 'Reg William', 'Full Professor', 'Nursing', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (27, 'Nonna Blackbrough', 'Assistant Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (28, 'Darb Jaimez', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (29, 'Gavan Schimon', 'Associate Professor', 'Computer Science', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (30, 'Minetta Outridge', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (31, 'Anatollo Towl', 'Associate Professor', 'Physics', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (32, 'Matelda Gitting', 'Associate Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (33, 'Loy Augustus', 'Assistant Professor', 'Nursing', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (34, 'Aland MacDiarmid', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (35, 'Thaddeus Whatmough', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (36, 'Ida Lindgren', 'Full Professor', 'Chemistry', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (37, 'Melisande Pegler', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (38, 'Zacherie Andryushin', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (39, 'Edgardo Dundendale', 'Associate Professor', 'Computer Science', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (40, 'Noel Haller', 'Associate Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (41, 'Cherianne Maly', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (42, 'Sukey Goodlip', 'Assistant Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (43, 'Manya Redmain', 'Associate Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (44, 'Corrianne MacAne', 'Full Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (45, 'Gustavus Eldin', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (46, 'Theressa Crosen', 'Full Professor', 'Physics', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (47, 'Eulalie Redihalgh', 'Associate Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (48, 'Andi Rodda', 'Full Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (49, 'Linnie Bilovsky', 'Full Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (50, 'Gwyn Esome', 'Assistant Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (51, 'Maible Bonnier', 'Associate Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (52, 'Natale McClunaghan', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (53, 'Keane Longwood', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (54, 'Forester Ribou', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (55, 'Far Keir', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (56, 'Theresina Jewis', 'Full Professor', 'Physics', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (57, 'Knox Sadry', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (58, 'Chaunce Careless', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (59, 'Maiga Iremonger', 'Assistant Professor', 'Chemistry', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (60, 'Peri Airey', 'Full Professor', 'Chemistry', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (61, 'Beth Bampkin', 'Assistant Professor', 'Physics', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (62, 'Milzie Broster', 'Associate Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (63, 'Kandace O'' Culligan', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (64, 'Candra Di Pietro', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (65, 'Casi Fackrell', 'Assistant Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (66, 'Matelda Napoleone', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (67, 'Vivi Meekin', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (68, 'Augustine Durtnal', 'Assistant Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (69, 'Marj Brandenburg', 'Assistant Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (70, 'Grange Smewin', 'Associate Professor', 'Nursing', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (71, 'Fidelity Stolte', 'Full Professor', 'Education', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (72, 'Valle Whatham', 'Associate Professor', 'Math', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (73, 'Bron Goodlip', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (74, 'Richart Bleything', 'Full Professor', 'Education', 'Male');
insert into Instructor (IID, name, title, dept, gender) values (75, 'Bonnie Bielfelt', 'Associate Professor', 'Nursing', 'Female');
insert into Instructor (IID, name, title, dept, gender) values (76, 'Zared Skittrall', 'Assistant Professor', 'Nursing', 'Male');
